### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by novatien** [ONLYOFFICE/documents-app-android#204] opened 2022-05-13 04:46 UTC
I can't run the app. Can I ask if I need to buy any sdk?

**Comment by ShockwaveNN** [comment] 2022-05-13 06:57
If you mean `run` to compile - it's a duplicate of https://github.com/ONLYOFFICE/documents-app-android/issues/32 and you need to contact sales@onlyoffice.com to discuss how to get all source codes

But if you got some troubles just running it on your device - please describe your problem in more details

**Comment by ShockwaveNN** [comment] 2022-06-24 15:21
This issue was closed due to no response.

**Closed by ShockwaveNN** 2022-06-24 15:21 UTC
