### ISSUE TITLE
Compile for android

### ISSUE THREAD

**Issue by hi589** [ONLYOFFICE/documents-app-android#32] opened 2021-05-04 13:55 UTC
**Describe your problem**:

Hello.

I want to compile ONLYOFFICE for android.

This documents-app-android project contains many so files.
[https://github.com/ONLYOFFICE/documents-app-android](url)

What should I compile for those so files?
Is there any guide for android?

Thank you.
Damir

**Comment by michael-efremov** [comment] 2021-05-04 14:32
Hi. 
Part of the source code are located in private repositories. You can't compile the project without them.

**Comment by hi589** [comment] 2021-05-04 16:53
Thank you @michael-efremov 

You mean that part of source code are for paid members?
or not ready for distribution?

Can you help me the android compiling?

Thanks.
Damir

**Comment by TheOneWithTheBraid** [comment] 2021-05-08 15:07
Do you plan to make these parts open source some day? It would be a great step for the whole open source community as ONLYOFFICE is by far the most feature-rich office application we know.

**Comment by meximan** [comment] 2021-09-19 15:10
Totally agree with @TheOneWithTheBraid

**Comment by itsmeboy0** [comment] 2022-05-29 02:45
Any update for this?

**Comment by mon-jai** [comment] 2022-06-25 20:55
@michael-efremov Isn't the source code available in the [public repo](https://github.com/ONLYOFFICE/web-apps/tree/master/apps/documenteditor/mobile)?

**Comment by gmankab** [comment] 2023-04-27 10:15
> Hi. Part of the source code are located in private repositories. You can't compile the project without them.

please open them

**Comment by Rita-Bubnova** [comment] 2024-03-13 13:11
Duplicate of https://github.com/ONLYOFFICE/documents-app-android/issues/287.

**Closed by Rita-Bubnova** 2024-03-13 13:11 UTC
